// Code generated by command: go run asm.go -out md5.s -stubs stub.go. DO NOT EDIT.

package md5

// block MD5 hashes the 64-byte message m into the running state h.
func block(h *[4]uint32, m []byte)
